// src/lib/components/AgreementModal.svelte
<script lang="ts">
  import { Modal } from '@skeletonlabs/skeleton-svelte';
  import * as icons from '@lucide/svelte';
  import { createAgreement } from '$lib/services/gameService';
  import type { Actor, ActorWithCard } from '$lib/types';
  import { toaster } from '$lib/utils/toaster-svelte';

  // Props
  const { gameId, actorsList } = $props<{
    gameId: string;
    actorsList: ActorWithCard[];
  }>();

  // State
  let modalOpen = $state(false);
  let selectedParties = $state<string[]>([]);
  let terms = $state<Record<string, { obligations: string[]; benefits: string[] }>>({});
  let newObligations = $state<Record<string, string>>({});
  let newBenefits = $state<Record<string, string>>({});
  let title = $state('');
  let description = $state('');
  let agreementType = $state<'symmetric' | 'asymmetric'>('asymmetric');
  let isSubmitting = $state(false);

  // Reset the form
  function resetForm() {
    title = '';
    description = '';
    selectedParties = [];
    terms = {};
    newObligations = {};
    newBenefits = {};
    agreementType = 'asymmetric';
    isSubmitting = false;
  }

  // Toggle party selection
  function toggleParty(actorId: string) {
    if (selectedParties.includes(actorId)) {
      // Remove actor and its terms
      selectedParties = selectedParties.filter(id => id !== actorId);
      const { [actorId]: _, ...restTerms } = terms;
      terms = restTerms;
      const { [actorId]: __, ...restObligations } = newObligations;
      newObligations = restObligations;
      const { [actorId]: ___, ...restBenefits } = newBenefits;
      newBenefits = restBenefits;
    } else {
      // Add actor with empty terms
      selectedParties = [...selectedParties, actorId];
      terms = {
        ...terms,
        [actorId]: { obligations: [], benefits: [] }
      };
      newObligations = { ...newObligations, [actorId]: '' };
      newBenefits = { ...newBenefits, [actorId]: '' };
    }
  }

  // Add a new obligation
  function addObligation(actorId: string) {
    if (!newObligations[actorId]?.trim()) return;
    
    terms = {
      ...terms,
      [actorId]: {
        ...terms[actorId],
        obligations: [...terms[actorId].obligations, newObligations[actorId]]
      }
    };
    newObligations = { ...newObligations, [actorId]: '' };
  }

  // Add a new benefit
  function addBenefit(actorId: string) {
    if (!newBenefits[actorId]?.trim()) return;
    
    terms = {
      ...terms,
      [actorId]: {
        ...terms[actorId],
        benefits: [...terms[actorId].benefits, newBenefits[actorId]]
      }
    };
    newBenefits = { ...newBenefits, [actorId]: '' };
  }

  // Remove an obligation
  function removeObligation(actorId: string, index: number) {
    terms = {
      ...terms,
      [actorId]: {
        ...terms[actorId],
        obligations: terms[actorId].obligations.filter((_, i) => i !== index)
      }
    };
  }

  // Remove a benefit
  function removeBenefit(actorId: string, index: number) {
    terms = {
      ...terms,
      [actorId]: {
        ...terms[actorId],
        benefits: terms[actorId].benefits.filter((_, i) => i !== index)
      }
    };
  }

  // Handle form submission
  async function handleSubmit() {
    console.log('Submitting form with data:', { 
      title, 
      description, 
      selectedParties, 
      terms: JSON.stringify(terms) 
    });
    
    // Form validation
    if (!title.trim()) {
      console.log('Validation error: Missing title');
      toaster.error({
        title: 'Validation Error',
        description: 'Please enter a title for the agreement',
        classes: 'bg-white dark:bg-gray-800 rounded border border-red-500 dark:border-red-700 shadow-lg'
      });
      return;
    }

    if (!description.trim()) {
      toaster.error({
        title: 'Validation Error',
        description: 'Please enter a description for the agreement',
        classes: 'bg-white dark:bg-gray-800 rounded border border-red-500 dark:border-red-700 shadow-lg'
      });
      return;
    }

    if (selectedParties.length < 1) {
      toaster.error({
        title: 'Validation Error',
        description: 'Please select at least one party for the agreement',
        classes: 'bg-white dark:bg-gray-800 rounded border border-red-500 dark:border-red-700 shadow-lg'
      });
      return;
    }

    // Validate that each party has at least one obligation or benefit
    for (const actorId of selectedParties) {
      if (terms[actorId].obligations.length === 0 && terms[actorId].benefits.length === 0) {
        const actor = actorsList.find(a => a.actor_id === actorId);
        toaster.error({
          title: 'Validation Error',
          description: `${actor?.custom_name || actor?.card?.role_title || 'Actor'} needs at least one obligation or benefit`,
          classes: 'bg-white dark:bg-gray-800 rounded border border-red-500 dark:border-red-700 shadow-lg'
        });
        return;
      }
    }

    isSubmitting = true;
    try {
      console.log('Creating agreement with:', {
        gameId,
        title,
        description,
        parties: selectedParties,
        terms
      });
      
      // Create agreement using gameService
      const result = await createAgreement(
        gameId,
        title,
        description,
        selectedParties,
        terms
      );
      
      console.log('Agreement creation result:', result);

      if (result) {
        toaster.success({
          title: 'Success',
          description: 'Agreement created successfully',
          classes: 'bg-white dark:bg-gray-800 rounded border border-green-500 dark:border-green-700 shadow-lg'
        });
        resetForm();
        modalOpen = false;
      } else {
        toaster.error({
          title: 'Error',
          description: 'Failed to create agreement',
          classes: 'bg-white dark:bg-gray-800 rounded border border-red-500 dark:border-red-700 shadow-lg'
        });
      }
    } catch (error) {
      console.error('Error creating agreement:', error);
      toaster.error({
        title: 'Error',
        description: 'An error occurred while creating the agreement',
        classes: 'bg-white dark:bg-gray-800 rounded border border-red-500 dark:border-red-700 shadow-lg'
      });
    } finally {
      isSubmitting = false;
    }
  }

  // Close the modal
  function closeModal() {
    resetForm();
    modalOpen = false;
  }

  // Open the modal
  export function openModal() {
    resetForm();
    modalOpen = true;
  }

  // Get actor name or title
  function getActorName(actorId: string) {
    const actor = actorsList.find(a => a.actor_id === actorId);
    return actor?.custom_name || actor?.card?.role_title || 'Unknown Actor';
  }
</script>

<Modal
  open={modalOpen}
  onOpenChange={(e) => (modalOpen = e.open)}
  backdropClasses="backdrop-blur-lg bg-surface-100-900/50"
>
  {#snippet trigger()}{/snippet}
  
  {#snippet content()}
    <div class="card bg-surface-50-950 p-4 space-y-4 shadow-xl backdrop-blur-sm border border-surface-200-700/30 max-w-screen-lg w-full max-h-[90vh] overflow-y-auto rounded-lg">
      <header class="flex justify-between items-center">
        <h2 class="h2 text-primary-700-300">Create New Agreement</h2>
        <button class="btn-icon variant-soft" onclick={closeModal}>
          <icons.X />
        </button>
      </header>
      
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <!-- Agreement Details -->
        <div class="space-y-4">
          <label class="label">
            <span>Agreement Title</span>
            <input 
              type="text" 
              class="input" 
              placeholder="Enter a memorable title..."
              bind:value={title}
            />
          </label>
          
          <label class="label">
            <span>Agreement Description</span>
            <textarea 
              class="textarea" 
              placeholder="Briefly describe this agreement..."
              rows="3"
              bind:value={description}
            ></textarea>
          </label>
          
          <div class="card bg-surface-100-800 p-4 space-y-2 border border-surface-200-700/30">
            <h3 class="h3 text-primary-700-300">Agreement Type</h3>
            <div class="flex flex-col gap-2">
              <label class="flex items-center space-x-2">
                <input 
                  type="radio" 
                  name="agreement-type" 
                  value="asymmetric" 
                  checked={agreementType === 'asymmetric'}
                  onchange={() => agreementType = 'asymmetric'} 
                />
                <span>Asymmetric (Different obligations and benefits)</span>
              </label>
              <label class="flex items-center space-x-2">
                <input 
                  type="radio" 
                  name="agreement-type" 
                  value="symmetric" 
                  checked={agreementType === 'symmetric'}
                  onchange={() => agreementType = 'symmetric'} 
                />
                <span>Symmetric (Shared obligations and benefits)</span>
              </label>
            </div>
          </div>
        </div>
        
        <!-- Party Selection -->
        <div class="card bg-surface-100-800 p-4 space-y-4 border border-surface-200-700/30">
          <h3 class="h3 text-primary-700-300">Select Parties</h3>
          <div class="max-h-40 overflow-y-auto space-y-2">
            {#each actorsList as actor}
              <div class="flex items-center space-x-2">
                <button 
                  class="btn {selectedParties.includes(actor.actor_id) ? 'variant-filled-primary' : 'variant-soft'} btn-sm"
                  onclick={() => toggleParty(actor.actor_id)}
                >
                  {selectedParties.includes(actor.actor_id) ? '✓' : '+'}
                </button>
                <span>{actor.custom_name || actor.card?.role_title || 'Unnamed Actor'}</span>
                {#if actor.card?.card_category}
                  <span class="badge variant-soft">{actor.card.card_category}</span>
                {/if}
              </div>
            {/each}
          </div>
        </div>
      </div>
      
      <!-- Terms Section - Only show if parties are selected -->
      {#if selectedParties.length > 0}
        <div class="card bg-surface-100-800 p-4 space-y-4 border border-surface-200-700/30">
          <h3 class="h3 text-primary-700-300">Agreement Terms</h3>
          <div class="space-y-6">
            {#each selectedParties as actorId}
              <div class="card bg-surface-200-700 p-4 border border-surface-300-600/30 shadow-sm">
                <h4 class="h4 mb-2 text-secondary-700-300">{getActorName(actorId)}</h4>
                
                <!-- Obligations -->
                <div class="mb-4">
                  <h5 class="h5 text-primary-600-400">Obligations</h5>
                  <!-- Add new obligation -->
                  <div class="flex items-center space-x-2 mb-2">
                    <input 
                      type="text" 
                      class="input" 
                      placeholder="What must this actor provide or do?"
                      bind:value={newObligations[actorId]}
                      onkeydown={(e) => e.key === 'Enter' && addObligation(actorId)}
                    />
                    <button 
                      class="btn-icon variant-filled-primary"
                      onclick={() => addObligation(actorId)}
                    >
                      <icons.Plus />
                    </button>
                  </div>
                  
                  <!-- List of obligations -->
                  <ul class="list-disc list-inside space-y-1">
                    {#each terms[actorId]?.obligations || [] as obligation, i}
                      <li class="flex items-center justify-between">
                        <span>{obligation}</span>
                        <button 
                          class="btn-icon variant-soft-error btn-sm"
                          onclick={() => removeObligation(actorId, i)}
                        >
                          <icons.Trash2 class="w-4 h-4" />
                        </button>
                      </li>
                    {/each}
                  </ul>
                </div>
                
                <!-- Benefits -->
                <div>
                  <h5 class="h5 text-secondary-600-400">Benefits</h5>
                  <!-- Add new benefit -->
                  <div class="flex items-center space-x-2 mb-2">
                    <input 
                      type="text" 
                      class="input" 
                      placeholder="What does this actor receive?"
                      bind:value={newBenefits[actorId]}
                      onkeydown={(e) => e.key === 'Enter' && addBenefit(actorId)}
                    />
                    <button 
                      class="btn-icon variant-filled-secondary"
                      onclick={() => addBenefit(actorId)}
                    >
                      <icons.Plus />
                    </button>
                  </div>
                  
                  <!-- List of benefits -->
                  <ul class="list-disc list-inside space-y-1">
                    {#each terms[actorId]?.benefits || [] as benefit, i}
                      <li class="flex items-center justify-between">
                        <span>{benefit}</span>
                        <button 
                          class="btn-icon variant-soft-error btn-sm"
                          onclick={() => removeBenefit(actorId, i)}
                        >
                          <icons.Trash2 class="w-4 h-4" />
                        </button>
                      </li>
                    {/each}
                  </ul>
                </div>
              </div>
            {/each}
          </div>
        </div>
      {/if}
      
      <footer class="flex justify-end gap-4">
        <button type="button" class="btn variant-soft" onclick={closeModal}>Cancel</button>
        <button 
          type="button" 
          class="btn variant-filled-primary" 
          onclick={handleSubmit}
          disabled={isSubmitting}
        >
          {#if isSubmitting}
            <icons.Loader class="animate-spin mr-2" />
            Creating...
          {:else}
            Create Agreement
          {/if}
        </button>
      </footer>
    </div>
  {/snippet}
</Modal>

// static/ReactReference/AgreementModal.tsx
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { X, Plus, Trash2 } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';
import useGameStore, { AgreementType } from '@/store/gameStore';
import { v4 as uuidv4 } from 'uuid';

const agreementSchema = z.object({
  title: z.string().min(3, "Title is required"),
  summary: z.string().min(10, "Summary should be at least 10 characters"),
  type: z.enum(["Bilateral", "Multilateral", "Symmetric", "Asymmetric"]),
});

type AgreementFormValues = z.infer<typeof agreementSchema>;

type PartyTerms = {
  actorId: string;
  obligations: { id: string; text: string }[];
  benefits: { id: string; text: string }[];
};

export default function AgreementModal() {
  const { 
    actors, 
    showAgreementModal, 
    toggleAgreementModal, 
    addAgreement 
  } = useGameStore();
  
  const [selectedParties, setSelectedParties] = useState<string[]>([]);
  const [partyTerms, setPartyTerms] = useState<Record<string, PartyTerms>>({});
  const [newObligation, setNewObligation] = useState<Record<string, string>>({});
  const [newBenefit, setNewBenefit] = useState<Record<string, string>>({});
  
  const { register, handleSubmit, reset, watch, formState: { errors } } = useForm<AgreementFormValues>({
    resolver: zodResolver(agreementSchema),
    defaultValues: {
      title: '',
      summary: '',
      type: 'Bilateral',
    }
  });
  
  const agreementType = watch('type');

  const resetForm = () => {
    reset();
    setSelectedParties([]);
    setPartyTerms({});
    setNewObligation({});
    setNewBenefit({});
  };
  
  const handleClose = () => {
    resetForm();
    toggleAgreementModal();
  };
  
  const toggleParty = (actorId: string) => {
    setSelectedParties(prev => {
      if (prev.includes(actorId)) {
        // Remove actor and its terms
        const { [actorId]: _, ...rest } = partyTerms;
        setPartyTerms(rest);
        return prev.filter(id => id !== actorId);
      } else {
        // Add actor with empty terms
        setPartyTerms(prev => ({
          ...prev,
          [actorId]: {
            actorId,
            obligations: [],
            benefits: []
          }
        }));
        return [...prev, actorId];
      }
    });
  };
  
  const addPartyObligation = (actorId: string) => {
    if (!newObligation[actorId]?.trim()) return;
    
    setPartyTerms(prev => ({
      ...prev,
      [actorId]: {
        ...prev[actorId],
        obligations: [
          ...prev[actorId].obligations,
          { id: uuidv4(), text: newObligation[actorId] }
        ]
      }
    }));
    
    setNewObligation(prev => ({
      ...prev,
      [actorId]: ''
    }));
  };
  
  const removePartyObligation = (actorId: string, obligationId: string) => {
    setPartyTerms(prev => ({
      ...prev,
      [actorId]: {
        ...prev[actorId],
        obligations: prev[actorId].obligations.filter(o => o.id !== obligationId)
      }
    }));
  };
  
  const addPartyBenefit = (actorId: string) => {
    if (!newBenefit[actorId]?.trim()) return;
    
    setPartyTerms(prev => ({
      ...prev,
      [actorId]: {
        ...prev[actorId],
        benefits: [
          ...prev[actorId].benefits,
          { id: uuidv4(), text: newBenefit[actorId] }
        ]
      }
    }));
    
    setNewBenefit(prev => ({
      ...prev,
      [actorId]: ''
    }));
  };
  
  const removePartyBenefit = (actorId: string, benefitId: string) => {
    setPartyTerms(prev => ({
      ...prev,
      [actorId]: {
        ...prev[actorId],
        benefits: prev[actorId].benefits.filter(b => b.id !== benefitId)
      }
    }));
  };
  
  const onSubmit = (data: AgreementFormValues) => {
    // Validate that we have parties selected
    if (selectedParties.length === 0) {
      return; // Already handled by the disabled button
    }
    
    // Format obligations and benefits for the agreement
    const obligations = Object.values(partyTerms).flatMap(party => 
      party.obligations.map(obligation => ({
        id: obligation.id,
        description: obligation.text, // Changed from text to description
        fromActorId: party.actorId,
      }))
    );
    
    const benefits = Object.values(partyTerms).flatMap(party => 
      party.benefits.map(benefit => ({
        id: benefit.id,
        description: benefit.text, // Changed from text to description
        toActorId: party.actorId,
      }))
    );
    
    // Create the new agreement
    const newAgreement = {
      id: uuidv4(),
      title: data.title,
      summary: data.summary,
      type: data.type as AgreementType,
      parties: selectedParties,
      obligations,
      benefits,
      position: { x: 200, y: 200 }
    };
    
    // Log the agreement being created for debugging
    console.log("Creating new agreement:", newAgreement);
    
    // Add to store and close modal
    addAgreement(newAgreement);
    handleClose();
  };

  const getActorName = (actorId: string) => {
    return actors.find(actor => actor.id === actorId)?.name || 'Unknown Actor';
  };
  
  return (
    <Dialog open={showAgreementModal} onOpenChange={handleClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto bg-[#FCFCF7]">
        <DialogHeader>
          <DialogTitle className="text-xl font-bold">Create New Agreement</DialogTitle>
        </DialogHeader>
        
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          {/* Agreement Basic Info */}
          <div>
            <Label htmlFor="title">Agreement Title</Label>
            <Input
              id="title"
              placeholder="Enter a memorable title..."
              {...register('title')}
              className="w-full"
            />
            {errors.title && (
              <p className="text-xs text-red-500 mt-1">{errors.title.message}</p>
            )}
          </div>
          
          <div>
            <Label htmlFor="summary">Agreement Summary</Label>
            <Textarea
              id="summary"
              placeholder="Briefly describe this agreement..."
              rows={2}
              {...register('summary')}
              className="w-full"
            />
            {errors.summary && (
              <p className="text-xs text-red-500 mt-1">{errors.summary.message}</p>
            )}
          </div>
          
          {/* Agreement Type */}
          <div>
            <Label>Agreement Type</Label>
            <RadioGroup defaultValue="Bilateral" {...register('type')} className="grid grid-cols-2 gap-3 mt-1">
              <div className={`border rounded p-3 cursor-pointer hover:border-primary flex items-center ${agreementType === 'Bilateral' ? 'border-primary bg-primary/5' : ''}`}>
                <RadioGroupItem id="bilateral" value="Bilateral" className="mr-2" />
                <div>
                  <Label htmlFor="bilateral" className="font-medium">Bilateral</Label>
                  <p className="text-xs text-gray-500">Between two parties</p>
                </div>
              </div>
              
              <div className={`border rounded p-3 cursor-pointer hover:border-primary flex items-center ${agreementType === 'Multilateral' ? 'border-primary bg-primary/5' : ''}`}>
                <RadioGroupItem id="multilateral" value="Multilateral" className="mr-2" />
                <div>
                  <Label htmlFor="multilateral" className="font-medium">Multilateral</Label>
                  <p className="text-xs text-gray-500">Three or more parties</p>
                </div>
              </div>
              
              <div className={`border rounded p-3 cursor-pointer hover:border-primary flex items-center ${agreementType === 'Symmetric' ? 'border-primary bg-primary/5' : ''}`}>
                <RadioGroupItem id="symmetric" value="Symmetric" className="mr-2" />
                <div>
                  <Label htmlFor="symmetric" className="font-medium">Symmetric</Label>
                  <p className="text-xs text-gray-500">Equal terms for all parties</p>
                </div>
              </div>
              
              <div className={`border rounded p-3 cursor-pointer hover:border-primary flex items-center ${agreementType === 'Asymmetric' ? 'border-primary bg-primary/5' : ''}`}>
                <RadioGroupItem id="asymmetric" value="Asymmetric" className="mr-2" />
                <div>
                  <Label htmlFor="asymmetric" className="font-medium">Asymmetric</Label>
                  <p className="text-xs text-gray-500">Unequal terms between parties</p>
                </div>
              </div>
            </RadioGroup>
          </div>
          
          {/* Parties Involved */}
          <div>
            <Label>Parties Involved</Label>
            <div className="flex flex-wrap gap-2 mb-2">
              {selectedParties.map(actorId => (
                <span key={actorId} className="bg-primary/10 text-primary-dark dark:text-primary-light px-2 py-1 rounded-full text-sm flex items-center">
                  {getActorName(actorId)}
                  <Button 
                    type="button"
                    variant="ghost" 
                    size="icon" 
                    onClick={() => toggleParty(actorId)}
                    className="ml-1 text-primary-dark/70 hover:text-primary-dark dark:text-primary-light/70 dark:hover:text-primary-light h-5 w-5 p-0"
                  >
                    <X className="h-3 w-3" />
                  </Button>
                </span>
              ))}
            </div>
            
            <div className="mb-4">
              <Label>Available Actors</Label>
              <div className="flex flex-wrap gap-2 mt-1">
                {actors.map(actor => (
                  <Button
                    key={actor.id}
                    type="button"
                    variant={selectedParties.includes(actor.id) ? "secondary" : "outline"}
                    size="sm"
                    onClick={() => toggleParty(actor.id)}
                    className="text-sm"
                  >
                    {actor.name}
                  </Button>
                ))}
              </div>
            </div>
          </div>
          
          {/* Agreement Details - Per Party */}
          {selectedParties.length > 0 && (
            <div className="space-y-4">
              {selectedParties.map(actorId => (
                <div key={actorId} className="border rounded-lg p-4 bg-white">
                  <h3 className="font-medium mb-3">{getActorName(actorId)}</h3>
                  
                  <div className="mb-3">
                    <Label className="text-sm font-medium mb-1">Obligations</Label>
                    <div className="flex items-center space-x-2 mb-2">
                      <Input
                        type="text"
                        placeholder="Add an obligation..."
                        value={newObligation[actorId] || ''}
                        onChange={(e) => setNewObligation(prev => ({ ...prev, [actorId]: e.target.value }))}
                        className="flex-grow"
                      />
                      <Button
                        type="button"
                        onClick={() => addPartyObligation(actorId)}
                        className="bg-primary hover:bg-primary-dark text-white p-2 h-9 w-9"
                      >
                        <Plus className="h-4 w-4" />
                      </Button>
                    </div>
                    
                    <ul className="space-y-1">
                      {partyTerms[actorId]?.obligations.map(obligation => (
                        <li key={obligation.id} className="flex items-center justify-between bg-primary/5 dark:bg-primary/10 p-2 rounded">
                          <span className="text-sm">{obligation.text}</span>
                          <Button
                            type="button"
                            variant="ghost"
                            size="icon"
                            onClick={() => removePartyObligation(actorId, obligation.id)}
                            className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300 h-6 w-6"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </li>
                      ))}
                    </ul>
                  </div>
                  
                  <div>
                    <Label className="text-sm font-medium mb-1">Benefits</Label>
                    <div className="flex items-center space-x-2 mb-2">
                      <Input
                        type="text"
                        placeholder="Add a benefit..."
                        value={newBenefit[actorId] || ''}
                        onChange={(e) => setNewBenefit(prev => ({ ...prev, [actorId]: e.target.value }))}
                        className="flex-grow"
                      />
                      <Button
                        type="button"
                        onClick={() => addPartyBenefit(actorId)}
                        className="bg-accent hover:bg-accent-dark text-white p-2 h-9 w-9"
                      >
                        <Plus className="h-4 w-4" />
                      </Button>
                    </div>
                    
                    <ul className="space-y-1">
                      {partyTerms[actorId]?.benefits.map(benefit => (
                        <li key={benefit.id} className="flex items-center justify-between bg-accent/5 dark:bg-accent/10 p-2 rounded">
                          <span className="text-sm">{benefit.text}</span>
                          <Button
                            type="button"
                            variant="ghost"
                            size="icon"
                            onClick={() => removePartyBenefit(actorId, benefit.id)}
                            className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300 h-6 w-6"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>
          )}
          
          <DialogFooter className="mt-4 space-x-3">
            <Button type="button" variant="outline" onClick={handleClose}>
              Cancel
            </Button>
            <Button 
              type="submit"
              disabled={selectedParties.length === 0}
              className="bg-primary hover:bg-primary-dark text-white flex items-center"
            >
              Create Agreement
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
