// src/lib/components/game/NodeDetailsPanel.svelte
<script lang="ts">
  import { gameStore } from '@/store/gameStore';
  import type { Actor, Agreement } from '@/store/gameStore';
  import { X } from 'lucide-svelte';
  
  let selectedNode: Actor | Agreement | null = null;
  let selectedNodeType: 'actor' | 'agreement' | null = null;
  let actors: Actor[] = [];
  
  // Subscribe to stores
  const unsubscribeNode = gameStore.selectedNode.subscribe(value => {
    selectedNode = value;
  });
  
  const unsubscribeNodeType = gameStore.selectedNodeType.subscribe(value => {
    selectedNodeType = value;
  });
  
  const unsubscribeActors = gameStore.actors.subscribe(value => {
    actors = value;
  });
  
  function closeDetails() {
    gameStore.selectedNodeId.set(null);
    gameStore.selectedNodeType.set(null);
  }
  
  function getActorName(actorId: string): string {
    const actor = actors.find(a => a.id === actorId);
    return actor ? actor.name : 'Unknown Actor';
  }
</script>

{#if selectedNode}
  <div class="details-panel absolute top-0 right-0 w-72 h-full p-4 z-10 overflow-auto">
    <div class="flex justify-between items-center mb-4">
      <h2 class="font-semibold text-lg">
        {selectedNodeType === 'actor' ? 'Actor Details' : 'Agreement Details'}
      </h2>
      <button 
        on:click={closeDetails}
        class="w-6 h-6 flex items-center justify-center rounded-md hover:bg-gray-200"
        aria-label="Close Details"
      >
        <X class="w-4 h-4 text-gray-700" />
      </button>
    </div>
    
    {#if selectedNodeType === 'actor'}
      {@const actor = selectedNode as Actor}
      <div class="space-y-4">
        <div>
          <h3 class="text-xl font-medium text-gray-800">{actor.name}</h3>
          <div class="text-sm text-gray-600 mt-1">Role: {actor.role}</div>
        </div>
        
        <div>
          <h4 class="font-medium text-gray-700 mb-1">Description</h4>
          <p class="text-sm text-gray-600">{actor.description}</p>
        </div>
      </div>
      
    {:else if selectedNodeType === 'agreement'}
      {@const agreement = selectedNode as Agreement}
      <div class="space-y-4">
        <div>
          <h3 class="text-xl font-medium text-gray-800">{agreement.title}</h3>
          <div class="text-sm text-gray-600 mt-1">Type: {agreement.type}</div>
        </div>
        
        <div>
          <h4 class="font-medium text-gray-700 mb-1">Summary</h4>
          <p class="text-sm text-gray-600">{agreement.summary}</p>
        </div>
        
        <div>
          <h4 class="font-medium text-gray-700 mb-1">Parties</h4>
          <ul class="space-y-1">
            {#each agreement.parties as partyId}
              <li class="text-sm px-2 py-1 rounded bg-gray-100">{getActorName(partyId)}</li>
            {/each}
          </ul>
        </div>
        
        <div>
          <h4 class="font-medium text-gray-700 mb-1">Obligations</h4>
          <ul class="space-y-1">
            {#each agreement.obligations as obligation}
              <li class="text-sm rounded p-2 bg-primary/5 border-l-2 border-primary">
                <div class="font-medium">{getActorName(obligation.fromActorId)}</div>
                <div>{obligation.description}</div>
              </li>
            {/each}
          </ul>
        </div>
        
        <div>
          <h4 class="font-medium text-gray-700 mb-1">Benefits</h4>
          <ul class="space-y-1">
            {#each agreement.benefits as benefit}
              <li class="text-sm rounded p-2 bg-accent/5 border-l-2 border-accent">
                <div class="font-medium">{getActorName(benefit.toActorId)}</div>
                <div>{benefit.description}</div>
              </li>
            {/each}
          </ul>
        </div>
      </div>
    {/if}
  </div>
{/if}

// static/ReactReference/NodeDetailsPanel.tsx
import { useState } from 'react';
import { X, Edit } from 'lucide-react';
import { Button } from '@/components/ui/button';
import useGameStore from '@/store/gameStore';

export default function NodeDetailsPanel() {
  const { 
    showNodeDetailsPanel, 
    toggleNodeDetailsPanel, 
    selectedNodeId, 
    selectedNodeType, 
    actors, 
    agreements, 
    clearSelectedNode,
    selectNode
  } = useGameStore();
  
  const [showEdit, setShowEdit] = useState(false);
  
  if (!selectedNodeId || !selectedNodeType) return null;
  
  const handleClose = () => {
    clearSelectedNode();
  };
  
  const handleEditClick = () => {
    setShowEdit(true);
    // Implementation would open edit form for the current node
  };
  
  if (selectedNodeType === 'actor') {
    const actor = actors.find(a => a.id === selectedNodeId);
    if (!actor) return null;
    
    return (
      <div className={`absolute bottom-4 right-4 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-xl w-80 z-40 ${!showNodeDetailsPanel ? 'hidden' : ''}`}>
        <div className="flex justify-between items-center p-3 border-b border-gray-200 dark:border-gray-700">
          <h3 className="font-serif font-medium">{actor.name}</h3>
          <div className="flex items-center space-x-1">
            <Button 
              variant="ghost" 
              size="icon" 
              onClick={handleEditClick}
              className="p-1 rounded h-7 w-7"
            >
              <Edit className="h-4 w-4" />
            </Button>
            <Button 
              variant="ghost" 
              size="icon" 
              onClick={handleClose}
              className="p-1 rounded h-7 w-7"
            >
              <X className="h-4 w-4" />
            </Button>
          </div>
        </div>
        
        <div className="p-3 max-h-[50vh] overflow-y-auto">
          <div className="space-y-3">
            <div>
              <span className="text-xs font-medium text-secondary">Backstory</span>
              <p className="text-sm">{actor.backstory}</p>
            </div>
            
            <div>
              <span className="text-xs font-medium text-secondary">Values</span>
              <p className="text-sm">{actor.values}</p>
            </div>
            
            <div>
              <span className="text-xs font-medium text-secondary">Goals</span>
              <p className="text-sm">{actor.goals}</p>
            </div>
            
            <div>
              <span className="text-xs font-medium text-secondary">Obligations</span>
              <p className="text-sm">{actor.obligations}</p>
            </div>
            
            <div>
              <span className="text-xs font-medium text-secondary">Capabilities</span>
              <ul className="mt-1 list-disc list-inside">
                {actor.capabilities.map((capability, index) => (
                  <li key={index} className="text-xs">{capability}</li>
                ))}
              </ul>
            </div>
            
            <div>
              <span className="text-xs font-medium text-secondary">Resources</span>
              <ul className="mt-1 list-disc list-inside">
                {actor.resources.map((resource, index) => (
                  <li key={index} className="text-xs">{resource}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>
    );
  } else {
    // Agreement details
    const agreement = agreements.find(a => a.id === selectedNodeId);
    if (!agreement) return null;
    
    return (
      <div className={`absolute bottom-4 right-4 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-xl w-80 z-40 ${!showNodeDetailsPanel ? 'hidden' : ''}`}>
        <div className="flex justify-between items-center p-3 border-b border-gray-200 dark:border-gray-700">
          <h3 className="font-serif font-medium">{agreement.title}</h3>
          <div className="flex items-center space-x-1">
            <Button 
              variant="ghost" 
              size="icon" 
              onClick={handleEditClick}
              className="p-1 rounded h-7 w-7"
            >
              <Edit className="h-4 w-4" />
            </Button>
            <Button 
              variant="ghost" 
              size="icon" 
              onClick={handleClose}
              className="p-1 rounded h-7 w-7"
            >
              <X className="h-4 w-4" />
            </Button>
          </div>
        </div>
        
        <div className="p-3 max-h-[50vh] overflow-y-auto">
          <div className="space-y-3">
            <div>
              <span className="text-xs font-medium text-secondary">Description</span>
              <p className="text-sm">{agreement.summary}</p>
            </div>
            
            <div>
              <span className="text-xs font-medium text-secondary">Parties Involved</span>
              <div className="mt-1 space-y-1">
                {agreement.parties.map(partyId => {
                  const actor = actors.find(a => a.id === partyId);
                  return (
                    <div key={partyId} className="flex items-center justify-between text-sm">
                      <span>{actor?.name || 'Unknown Actor'}</span>
                      <Button 
                        variant="link" 
                        size="sm" 
                        onClick={() => {
                          clearSelectedNode();
                          setTimeout(() => selectNode(partyId, 'actor'), 100);
                        }}
                        className="text-primary hover:text-primary-dark text-xs h-6"
                      >
                        View Details
                      </Button>
                    </div>
                  );
                })}
              </div>
            </div>
            
            <div>
              <span className="text-xs font-medium text-secondary">Agreement Terms</span>
              <div className="mt-1 space-y-3">
                <div>
                  <div className="text-xs font-medium text-primary flex items-center">
                    <span className="mr-1">→</span>
                    Obligations
                  </div>
                  <ul className="mt-1 space-y-1">
                    {agreement.obligations.map(obligation => (
                      <li key={obligation.id} className="text-xs bg-primary/5 dark:bg-primary/10 p-1.5 rounded">
                        {obligation.description}
                        <span className="block text-[10px] text-gray-500 mt-1">
                          From: {actors.find(a => a.id === obligation.fromActorId)?.name || 'Unknown Actor'}
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>
                
                <div>
                  <div className="text-xs font-medium text-accent flex items-center">
                    <span className="mr-1">←</span>
                    Benefits
                  </div>
                  <ul className="mt-1 space-y-1">
                    {agreement.benefits.map(benefit => (
                      <li key={benefit.id} className="text-xs bg-accent/5 dark:bg-accent/10 p-1.5 rounded">
                        {benefit.description}
                        <span className="block text-[10px] text-gray-500 mt-1">
                          To: {actors.find(a => a.id === benefit.toActorId)?.name || 'Unknown Actor'}
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
