// src/lib/components/game/SidebarMenu.svelte
<script lang="ts">
  import { Menu, X } from 'svelte-lucide';
  
  // Bind this to make it controllable from parent component
  export let showSidebar = false;
  
  function toggleSidebar() {
    showSidebar = !showSidebar;
  }
</script>

<div class="sidebar-menu fixed left-4 top-4 z-50 md:hidden">
  {#if !showSidebar}
    <button 
      on:click={toggleSidebar}
      class="w-10 h-10 flex items-center justify-center bg-white rounded-full shadow-md hover:bg-gray-100"
      aria-label="Open Sidebar"
    >
      <Menu class="w-5 h-5 text-gray-700" />
    </button>
  {:else}
    <button 
      on:click={toggleSidebar}
      class="w-10 h-10 flex items-center justify-center bg-white rounded-full shadow-md hover:bg-gray-100"
      aria-label="Close Sidebar"
    >
      <X class="w-5 h-5 text-gray-700" />
    </button>
  {/if}
</div>

// static/ReactReference/SidebarMenu.tsx
import { useState } from 'react';
import { Menu, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import PlayerSidebar from './PlayerSidebar';

export default function SidebarMenu() {
  const [isOpen, setIsOpen] = useState(false);

  const toggleSidebar = () => {
    setIsOpen(!isOpen);
  };

  return (
    <>
      {/* Hamburger toggle button - only visible when sidebar is closed */}
      {!isOpen && (
        <div className="absolute top-20 left-4 z-40">
          <Button
            variant="outline"
            size="icon"
            onClick={toggleSidebar}
            className="h-10 w-10 rounded-full bg-white shadow-md border border-gray-200"
            aria-label="Open sidebar"
          >
            <Menu className="h-5 w-5" />
          </Button>
        </div>
      )}

      {/* Sidebar with slide-in animation */}
      <div
        className={`fixed top-0 left-0 h-full z-30 transform transition-transform duration-300 ease-in-out ${
          isOpen ? 'translate-x-0' : '-translate-x-full'
        }`}
      >
        <PlayerSidebar onClose={toggleSidebar} />
      </div>

      {/* Overlay when sidebar is open - click to close */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black bg-opacity-30 z-20"
          onClick={toggleSidebar}
          aria-hidden="true"
        />
      )}
    </>
  );
}
